name: Test
description: Test

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo GitHub
        echo "${{ toJSON(github) }}"
        echo Context
        echo "${{ toJSON(context) }}"
        echo Job
        echo "${{ toJSON(job) }}"
        echo Env
        env
        echo '# Hello
        
        ## World

        :world_map: things

        * things
        * more

        a | b
        -|-
        c | d

        ' > "$GITHUB_STEP_SUMMARY"
