name: Test
description: Test

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo Event Path
        cat "$GITHUB_EVENT_PATH"
        echo GitHub
        echo "${{ toJSON(github) }}"
        echo Job
        echo "${{ toJSON(job) }}"
        echo Steps
        echo "${{ toJSON(steps) }}"
        echo Env
        env
        echo '# Hello
        
        ## World

        :world_map: things

        * things
        * more

        a | b
        -|-
        c | d

        ' > "$GITHUB_STEP_SUMMARY"
